name = "smartscore-api"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2026-01-31"

[env.dev]
name = "smartscore-api-dev"
[env.dev.vars]
ENVIRONMENT = "dev"

[env.prod]
name = "smartscore-api-prod"
[env.prod.vars]
ENVIRONMENT = "prod"
